### ISSUE TITLE
Other Decks

### ISSUE THREAD

**Issue by zachleboeuf** [AdriaGual/marvel-snap-bot#15]
Not an issue, but I wasn't sure how else to contact you. It says the bot can play Kazoo with applied logic. Would it play other decks without applied logic? Kind of like Agatha but I could actually get boosters for other cards?

**Comment by AdriaGual** [comment]
I recommended kazoo just because kazoo benefits a lot of by playing a large amount of cards and a misplay doesn't hit that hard (playing a squirrel girl doesn't matter the location except if it's a field where the card gets destroyed xD), that's why I think a deck like this is more suitable to be played with the bot.

BUT
I made the bot thinking of being able to play ANY deck, you just need to configure it.

Let me explain a bit more:
There's a file called [cp_list.py](https://github.com/AdriaGual/marvel-snap-bot/blob/master/cp_list.py ) where you have to add the cards you wanna play with each value (the only important ones are `mana` and `cp_average`).
The bot will always try to play the card in hand with more `cp_average` and with enough mana to play it.

For the fields happens more or less the same, you have the file [field_list.py](https://github.com/AdriaGual/marvel-snap-bot/blob/master/field_list.py) where you can add the fields and the priority to play a card (example: if a field gives -3 to each card you play there, I will put a negative priority since I want to play there only if I have no other possibilities available).

After setting your new cards on the `cp_list.py`, you will need to teach the bot to recognize the new cards, this process is kinda manual and long but not difficult.

You have a script called [print_hand_cards.py](https://github.com/AdriaGual/marvel-snap-bot/blob/master/print_hand_cards.py), if you execute it with an instance of BS, you'll see a real time screenshot of the bottom part of the BS screen, then, you start playing a game, and every time you see a card of your new deck, you have to screenshot it (screenshot the python screen card, not the emulator one!) and save it in the data folder example (data/angela/1.png), the name of the screenshot doesn't matter, also, my recommendation is to just screenshot the center. You will need a bunch of screenshots (card when it's only 1 card, when it's 2 cards, 3, 4, 5, 6 and 7 and corner cases). That's why it's long, you will need at least 8 screenshots and on different situations for each card you want to play.

But it's just that (if you wanna always play a card when it has enough mana, just set mana to 0 and push the average_cp to 999).

I'm now playing a hela discard deck but not getting consistent, that's why I didn't push it (this deck has a huge problem if hela gets discarded before turn 6 and it happens quite often xD).

Hope it helps!

**Comment by Neyschka** [comment]
Not sure what I'm doing wrong. Trying to add a new card; have added it to cp_list and added a new folder of the same name to the data folder. Added a picture of the card in just about every situation I can think of to the folder but it's just never detected :(

**Comment by AdriaGual** [comment]
@Wibbles790 Probably is a resolution problem, try taking the screenshots with the script [print_hand_cards.py](https://github.com/AdriaGual/marvel-snap-bot/blob/master/print_hand_cards.py).

**Comment by paperc07** [comment]
@Wibbles790 did you ever figure this out?
