### ISSUE TITLE
Hear Me Out! LOL

### ISSUE THREAD

**Issue by paperc07** [AdriaGual/marvel-snap-bot#25]
I just got Agatha Harkness and I've seen this Agatha farm decks cause she plays the deck for you, couldn't we essentially run one of these decks and just import Agatha and it'll just farm for us and with the bot just auto queuing, I figure shit we might even be able to rank up better that way cause with the Agatha deck we probably have a legitimate shot at winning and leveling up?

**Comment by AdriaGual** [comment]
I had the same idea, bought instantly Agatha when I could.
Here's the problem: Agatha's AI is... just really really bad, she plays cards on fields where cards get destroyed like death's domain, also she plays herself whenever she can so, if there's a turn 7, Agatha won't play a card since she is already in play (same case if rival plays wave and we have 4 mana, it'll play herself and on turns 5 and 6 she won't play any card).

So yeah, Agatha was a great idea but till they don't improve their AI it's almost impossible to win.

**Comment by paperc07** [comment]
Ahh ok I will close this then lol
