### ISSUE TITLE
\images\x0cields

### ISSUE THREAD

**Issue by dgol1115** [AdriaGual/marvel-snap-bot#29]
when i start the bot, it all runs and gets where it needs to go, but when it attempts to start playing, i get this 
![mintty_Jm4i8sd02e](https://user-images.githubusercontent.com/20586145/215838724-8bbae364-96be-4fe0-b6a5-f16d581a9763.png)
not quite sure whats happening, any help is appreciated

**Comment by AdriaGual** [comment]
Can you share a screenshot of your `config.py` file?

**Comment by dgol1115** [comment]
![image](https://user-images.githubusercontent.com/20586145/215878908-d9e6f5d7-5d01-420a-b43c-4a5667741a58.png)
here you go!

**Comment by AdriaGual** [comment]
![image](https://user-images.githubusercontent.com/25803231/215884768-852cb9de-5203-4ecd-a89b-fa88f23345fb.png)

I've highlighted the errors I see on your config file.

First of all, the project_path has a `r` on the start, remove it.

Also, paths MUST be in double slashes ( \\\ ) 

So instead of:
`images_folder = 'C:\marvelbot\images' `
You have to put:
`images_folder = 'C:\\marvelbot\\images' `

Do that with all the highlighted paths and try again.

Hope it helps!

**Comment by dgol1115** [comment]
Thanks, that fixed it! seems to be running along nicely now.

**Comment by AdriaGual** [comment]
Great! If you have another problem like that, you can use the 'Discussions' tab so other people can also help you!
