### ISSUE TITLE
where is the adb path? 

### ISSUE THREAD

**Issue by pusheenp0wer** [AdriaGual/marvel-snap-bot#30]
From what I see you use Nox but in the readme it says that Bluestacks is used

**Comment by AdriaGual** [comment]
Yeah, that's basically because I didn't want to install the android sdk and Nox has a prebuild adb, just that.

If you have installed the android sdk, just search where you installed it and you'll find a 'platform-tools' folder, enter there, open a cmd and execute the command 'adb devices', if it returns something that isn't a not found error, then this is your adb path.

**Comment by pusheenp0wer** [comment]
then can i use the adb fron Nox?

**Comment by AdriaGual** [comment]
Nox has a prebuild adb, just go to the Nox/bin folder and execute 'adb devices', you will see something like that.
![image](https://user-images.githubusercontent.com/25803231/215886626-77ae7b1b-b9f6-4a96-968b-3098668447b3.png)

**Comment by AdriaGual** [comment]
Also I've opened the 'Discussions' tab, this kind of questions should go there, instead of the issues one.

**Comment by pusheenp0wer** [comment]
ok, thanks boss
