### ISSUE TITLE
How to pip install -r requirements.txt ?

### ISSUE THREAD

**Issue by Archerman888** [AdriaGual/marvel-snap-bot#8]
![image](https://user-images.githubusercontent.com/83743669/213108520-ccb74ba5-aaec-43a3-969d-4442e7758333.png)
I'm stuck on this.

**Comment by StevenSnow31** [comment]
hello, I'm also trying to figure out how to make this work haha 

in the **How to use:** there 4 programs you need to download:
git
openCV
bluestacks
python3

you will need to download and open git commands (can't be your computer cmd) then you will insert pip install -r requirements.txt on it. (just click on it since he actually posts the links to the 4 programs)

just make sure to follow the first steps, before doing that one since you need to download the files first.

if you figure out the next steps after that let me know hahaha I'm trying to figure out the rest haha

that's all I know so far, I'm stuck trying to figure out what the adb_patch and the tmp_patch (I'm guessing I do my own tmp patch? idk yet) lol good luck. let me know if you figure it out

**Comment by pusheenp0wer** [comment]
im stuck in the same problem
![imagen](https://user-images.githubusercontent.com/56763859/213131883-b04be88d-20cc-402c-9c66-87012fd75457.png)

**Comment by Archerman888** [comment]
After installed that all and use gitcmd got the same problem why ? t,t
![image](https://user-images.githubusercontent.com/83743669/213149656-5ca067bf-05d1-4ae8-ae47-45ae91871351.png)

**Comment by AdriaGual** [comment]
@Archerman888 , pip is the python package installer, in order to be able to use it, you need to install python (v. 3.8) and add the path to the environment variables [python path](https://www.javatpoint.com/how-to-set-python-path).

@StevenSnow31 the adb_path is the path where you have your bin of the ADB, usually is where you have installed Nox or Bluestacks, just check where it is by going to the corresponding folder and running `adb devices` or an adb command.
tmp_path is just a folder to store temporary data (usually I store screenshots and I delete them for space optimization)

Hope it helps!

**Comment by Archerman888** [comment]
and use this
pip install pyautogui
python -m pip install --upgrade pip
